web_python/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('verify-email/<str:email>', views.VerifyUserEmail.as_view(), name='verify-email'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('password-reset/', views.PasswordResetRequestView.as_view(), name='password-reset'),
    path('password-reset-confirm/', views.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('password-reset-confirm/<str:uidb64>/<str:token>/', views.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('set-new-password/', views.SetNewPasswordView.as_view(), name='set-new-password'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
]

web_python/search/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('search/', views.search, name='search'),
    path('search/history/', views.search_history, name='search_history'),

]

web_python/web_python/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/auth/', include('accounts.urls')),
    path('', include('web_base.urls')),
    path('', include('search.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web_python/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager
from rest_framework_simplejwt.tokens import RefreshToken
from django.core.validators import MinLengthValidator

# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=200, unique=True, verbose_name='Email Address')
    password = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    last_login = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()
    
    def __str__(self):
        return self.email
    
    def tokens(self):
        refresh = RefreshToken.for_user(self)
        return {
            'refresh': str(refresh),
            'access': str(refresh.access_token)
        }
    
    @property
    def get_full_name(self):
        return self.first_name + ' ' + self.last_name
    
    def set_password(self, raw_password: str | None) -> None:
        return super().set_password(raw_password)
    
    def set_verified(self):
        self.is_verified = True
        self.save()
    
    


class OneTimePassword(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    otp = models.CharField(max_length=6, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.otp
    

web_python/accounts/forms.py
from django import forms
from .models import User

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    repeat_password = forms.CharField(widget=forms.PasswordInput, label='Repeat Password')

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'password', 'repeat_password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        repeat_password = cleaned_data.get('repeat_password')
        if len(password) < 6:
            raise forms.ValidationError('Password must be at least 6 characters long.')
        if password != repeat_password:
            raise forms.ValidationError('Passwords do not match')
        return cleaned_data

class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        fields = ['email', 'password']
    
    # def clean(self):
    #     cleaned_data = super().clean()
    #     email = cleaned_data.get('email')
    #     password = cleaned_data.get('password')
    #     user = User.objects.filter(email=email).first()
    #     if not user:
    #         raise forms.ValidationError('User does not exist')
    #     if not user.check_password(password):
    #         raise forms.ValidationError('Invalid password')
    #     return cleaned_data
class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField()

    class Meta:
        fields = ['email']
    
    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        user = User.objects.filter(email=email).first()
        if not user:
            raise forms.ValidationError('User does not exist')
        return cleaned_data

class SetNewPasswordForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput, label='Email')
    current_password = forms.CharField(widget=forms.PasswordInput, label='Current Password')
    new_password = forms.CharField(widget=forms.PasswordInput, label='New Password')
    confirm_new_password = forms.CharField(widget=forms.PasswordInput, label='Confirm New Password')

    class Meta:
        fields = ['Email','Current Password', 'New Password', 'Confirm New Password']

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        current_password = cleaned_data.get('current_password')
        new_password = cleaned_data.get('new_password')
        confirm_new_password = cleaned_data.get('confirm_new_password')
        if len(new_password) < 6:
            raise forms.ValidationError('Password must be at least 6 characters long.')
        if new_password != confirm_new_password:
            raise forms.ValidationError('Passwords do not match')
        return cleaned_data

web_python/accounts/views.py
from django.shortcuts import render, redirect
from .models import User, OneTimePassword
from django.template.response import TemplateResponse
from django.http import JsonResponse, HttpResponse
from django.forms.models import model_to_dict
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from .serializers import UserRegisterSerializer, UserLoginSerializer, PasswordResetRequestSerializer, SetNewPasswordSerializer, LogoutUserSerializer, VerifyUserEmailSerializer
from rest_framework.generics import GenericAPIView
from .utils import send_otp_email, send_normal_email
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import smart_str, smart_bytes, DjangoUnicodeDecodeError
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from .forms import UserRegisterForm, UserLoginForm, PasswordResetRequestForm, SetNewPasswordForm
from rest_framework.exceptions import AuthenticationFailed
from rest_framework_simplejwt.tokens import RefreshToken
from django.forms import ValidationError
import uuid
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse

class RegisterView(GenericAPIView):
    serializer_class = UserRegisterSerializer
    
    def post(self, request):
        user_data = request.data
        serializer = self.get_serializer(data=user_data)
        form = UserRegisterForm(request.data)
        if serializer.is_valid() and form.is_valid():
            serializer.save()
            user = serializer.data
            site_domain = get_current_site(request).domain
            relative_link = reverse('verify-email', kwargs={'email': user['email']})
            abs_url = f'http://{site_domain}{relative_link}'
            email_body = f'Hello, \nClick on the link below to verify your email \n{abs_url}'
            data = {
                'body': email_body,
                'subject': 'Verify your email',
                'to_email': user['email']
            }
            send_normal_email(data)
            return TemplateResponse(request, 'login.html', {
                'message': 'User created successfully\nPlease verify your email to login. Check your email for the verification link',
                'form' : UserLoginForm(),
            }, status=status.HTTP_201_CREATED)
        else:
            form = UserRegisterForm(request.data)
            return TemplateResponse(request, 'register.html', {
                'form': form,
            }, status=status.HTTP_400_BAD_REQUEST)
    
    def get(self, request):
        form = UserRegisterForm()
        serializer = self.get_serializer()
        return TemplateResponse(request, 'register.html', {'form' : form} ,status=status.HTTP_200_OK)

class VerifyUserEmail(GenericAPIView):
    serializer_class = VerifyUserEmailSerializer
    def get(self, request, email):
        user = User.objects.get(email=email)
        user.set_verified()
        user.save()
        send_normal_email({
            'subject': 'Verification successful',
            'body': f'Your email has been verified',
            'to_email': user.email
        })
        return TemplateResponse(request, 'login.html', {
            'message': 'Email verified successfully',
            'form' : UserLoginForm()
        }, status=status.HTTP_200_OK)
    
class LoginUserView(GenericAPIView):
    serializer_class = UserLoginSerializer

    def post(self, request):
        user_data = request.data
        serializer = self.serializer_class(data=user_data, context={'request': request})
        form = UserLoginForm(request.data)
        try:
            serializer.is_valid(raise_exception=True)
            user = serializer.validated_data['user']

            refresh = RefreshToken.for_user(user)
            serializer.is_valid(raise_exception=True)
            user = serializer.validated_data['user']

            refresh = RefreshToken.for_user(user)
            response = Response({
                'message': 'Login successful',
                'tokens': {
                    'refresh': str(refresh),
                    'access': str(refresh.access_token),
                }
            }, status=status.HTTP_200_OK)
            request.session['access_token'] = str(refresh.access_token)
            request.session['refresh_token'] = str(refresh)
            request.session['user'] = {
                'id' : user.id,
                'first_name' : user.first_name,
                'last_name' : user.last_name,
            }
            return redirect('/')

        except AuthenticationFailed as e:
            form = UserLoginForm(request.data)
            form.add_error(None, str(e))
            return TemplateResponse(request, 'login.html', {
                'form': form,
            }, status=status.HTTP_400_BAD_REQUEST)
    
    def get(self, request):
        form = UserLoginForm()
        return TemplateResponse(request, 'login.html', {'form': form}, status=status.HTTP_200_OK)

class PasswordResetRequestView(GenericAPIView):
    serializer_class = PasswordResetRequestSerializer
    def post(self, request):
        user_data = request.data
        form = PasswordResetRequestForm(user_data)
        serializer = self.serializer_class(data=user_data, context={'request': request})
        try:
            serializer.is_valid(raise_exception=False)
        except ValidationError as e:
            form.add_error(None, str(e))
            return TemplateResponse(request, 'password_reset.html', {
                'form': form,
            }, status=status.HTTP_400_BAD_REQUEST)
        
        return TemplateResponse(request, 'password_reset.html',{
                'form': form,
                'message_': 'Password reset email sent'
            }, status=status.HTTP_200_OK)
      
        
    def get(self, request):
        form = PasswordResetRequestForm()
        return TemplateResponse(request, 'password_reset.html', {'form': form}, status=status.HTTP_200_OK)
    
class PasswordResetConfirmView(GenericAPIView):
    def get(self, request, uidb64, token):
        try:
            user_id = smart_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(id=user_id)
            if not PasswordResetTokenGenerator().check_token(user, token):
                return TemplateResponse(request, 'password_reset.html', {
                    'message': 'Token is invalid or has expired'
                }, status=status.HTTP_400_BAD_REQUEST)
            new_password = uuid.uuid4().hex
            user.set_password(new_password)
            user.save()
            send_normal_email({
                'subject': 'Password reset successful',
                'body': f'Your new password is {new_password}',
                'to_email': user.email
            })
            return redirect('/api/auth/login')
        except DjangoUnicodeDecodeError as e:
            return TemplateResponse(request, 'password_reset_confirm.html', {
                'message': 'Token is invalid or has expired'
            }, status=status.HTTP_400_BAD_REQUEST)
        
class SetNewPasswordView(GenericAPIView):
    permission_classes = [IsAuthenticated]
    serializer_class = SetNewPasswordSerializer

    def get(self, request):
        form = SetNewPasswordForm()
        return TemplateResponse(request, 'set_new_password.html', {
            'form' : form
        }, status=status.HTTP_200_OK)
    
    def post(self, request):
        refresh_token = request.session.get('refresh_token')
        if not refresh_token:
            auth_header = request.headers.get('Authorization')
            if auth_header and auth_header.startswith('Bearer '):
                refresh_token = auth_header.split(' ')[1]

        if not refresh_token:
            return Response({'detail': 'Refresh token is required'}, status=status.HTTP_400_BAD_REQUEST)
        
        user_data = request.data
        form = SetNewPasswordForm(user_data)
        serializer = self.serializer_class(data=user_data)
        try:
            serializer.is_valid(raise_exception=False)
        except ValidationError as e:
            form.add_error(None, str(e))
            return TemplateResponse(request, 'set_new_password.html', {
                'form': form,
            }, status=status.HTTP_400_BAD_REQUEST)
        serializer.save()
        return redirect('/')


class LogoutUserView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        refresh_token = request.session.get('refresh_token')
        if not refresh_token:
            auth_header = request.headers.get('Authorization')
            if auth_header and auth_header.startswith('Bearer '):
                refresh_token = auth_header.split(' ')[1]

        if not refresh_token:
            return Response({'detail': 'Refresh token is required'}, status=status.HTTP_400_BAD_REQUEST)
        serializer = LogoutUserSerializer(data={'refresh_token': refresh_token})
        serializer.is_valid(raise_exception=True)
        serializer.save()
        request.session.flush()
        return TemplateResponse(request, 'home.html', {}, status=status.HTTP_200_OK)

    # def post(self, request):
    #     refresh_token = request.data.get('refresh_token')
    #     if not refresh_token:
    #         auth_header = request.headers.get('Authorization')
    #         if auth_header and auth_header.startswith('Bearer '):
    #             refresh_token = auth_header.split(' ')[1]

    #     if not refresh_token:
    #         return Response({'detail': 'Refresh token is required'}, status=status.HTTP_400_BAD_REQUEST)
    #     serializer = LogoutUserSerializer(data={'refresh_token': refresh_token})
    #     serializer.is_valid(raise_exception=True)
    #     serializer.save()

web_python/accounts/templates/login.html
{% extends 'base.html' %}

{% load static %}
{% load form_tags %}

{% block content %}

<h1 class="display-4 text-center my-5">Login</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <form method="post" class="p-4 border rounded-3 bg-light shadow-sm">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_email" class="form-label">Email</label>
                    {{ form.email|add_class:"form-control" }}
                    {% if form.email.errors %}
                        <div class="text-danger">
                            {{ form.email.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_password" class="form-label">Password</label>
                    {{ form.password|add_class:"form-control" }}
                    {% if form.password.errors %}
                        <div class="text-danger">
                            {{ form.password.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="rememberMe" name="remember_me">
                    <label class="form-check-label" for="rememberMe">Remember me</label>
                </div>
                <button type="submit" class="btn btn-primary w-100">Login</button>
                <div class="d-flex justify-content-between align-items-center my-4">
                    <strong><a href="{% url 'password-reset' %}" class="btn btn-link p-0">Forgot password</a></strong>
                    <div class="d-flex align-items-center">
                        <p class="mb-0 me-2">Not a member?</p>
                        <strong><a href="{% url 'register' %}" class="btn btn-link p-0">Register</a></strong>
                    </div>
                </div>
                {% if message %} 
                    <div class="alert alert-success mt-3">
                        {{ message|linebreaksbr }}
                    </div>
                {% endif %}
                {% if form.non_field_errors %}
                    <div class="alert alert-danger mt-3">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

web_python/accounts/templates/password_reset.html
{% extends 'base.html' %}

{% load static %}

{% load form_tags %}

{% block content %}

<h1 class="display-4 text-center my-5">Password Reset</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <form method="post" class="p-4 border rounded-3 bg-light shadow-sm">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_email" class="form-label">Email</label>
                    {{ form.email|add_class:"form-control" }}
                    {% if form.email.errors %}
                        <div class="text-danger">
                            {{ form.email.errors }}
                        </div>
                    {% endif %}
                </div>
                <button type="submit" class="btn btn-primary w-100">Send Password Reset Email</button>
                {% if not form.errors and message_ %}
                    <div class="alert alert-success mt-3">
                        {{ message_ }}
                    </div>
                {% endif %}
                {% if form.non_field_errors %}
                    <div class="alert alert-danger mt-3">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

web_python/accounts/templates/register.html
{% extends 'base.html' %}

{% load static %}
{% load form_tags %}

{% block content %}

<h1 class="display-4 text-center my-5">Register</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <form method="post" class="p-4 border rounded-3 bg-light shadow-sm">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_email" class="form-label">Email</label>
                    {{ form.email|add_class:"form-control" }}
                    {% if form.email.errors %}
                        <div class="text-danger">
                            {{ form.email.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_first_name" class="form-label">First Name</label>
                    {{ form.first_name|add_class:"form-control" }}
                    {% if form.first_name.errors %}
                        <div class="text-danger">
                            {{ form.first_name.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_last_name" class="form-label">Last Name</label>
                    {{ form.last_name|add_class:"form-control" }}
                    {% if form.last_name.errors %}
                        <div class="text-danger">
                            {{ form.last_name.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_password" class="form-label">Password</label>
                    {{ form.password|add_class:"form-control" }}
                    {% if form.password.errors %}
                        <div class="text-danger">
                            {{ form.password.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_repeat_password" class="form-label">Repeat Password</label>
                    {{ form.repeat_password|add_class:"form-control" }}
                    {% if form.repeat_password.errors %}
                        <div class="text-danger">
                            {{ form.repeat_password.errors }}
                        </div>
                    {% endif %}
                </div>
                <button type="submit" class="btn btn-primary w-100">Register</button>
                {% if form.non_field_errors %}
                    <div class="alert alert-danger mt-3">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

web_python/accounts/templates/set_new_password.html
{% extends 'base.html' %}

{% load static %}
{% load form_tags %}

{% block content %}

<h1 class="display-4 text-center my-5">Set New Password</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <form method="post" class="p-4 border rounded-3 bg-light shadow-sm">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_email" class="form-label">Email</label>
                    {{ form.email|add_class:"form-control" }}
                    {% if form.email.errors %}
                        <div class="text-danger">
                            {{ form.email.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_current_password" class="form-label">Current Password</label>
                    {{ form.current_password|add_class:"form-control" }}
                    {% if form.email.errors %}
                        <div class="text-danger">
                            {{ form.email.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_new_password" class="form-label">New Password</label>
                    {{ form.new_password|add_class:"form-control" }}
                    {% if form.new_password.errors %}
                        <div class="text-danger">
                            {{ form.new_password.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_confirm_new_password" class="form-label">Confirm New Password</label>
                    {{ form.confirm_new_password|add_class:"form-control" }}
                    {% if form.confirm_new_password.errors %}
                        <div class="text-danger">
                            {{ form.confirm_new_password.errors }}
                        </div>
                    {% endif %}
                </div>
                <button type="submit" class="btn btn-primary w-100">Reset Password</button>

                {% if form.non_field_errors %}
                    <div class="alert alert-danger mt-3">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
            </form>
        </div>
    </div>
</div>

{% endblock %}